import {Player} from './player.js';
import {InputHandler} from './input.js';


window.addEventListener('load', ()=>{
    function handleFormSubmit(){
        console.log('yo here')
        alert('clicked man')
        document.getElementById("myForm").submit();
    }

    const canvas = document.getElementById("canvas1");
    const ctx = canvas.getContext('2d');
    canvas.width = 1500;
    canvas.height = 500;
    class Game{
        constructor(width, height){
            this.width = width
            this.height = height
            this.player = new Player(this);
            this.input = new InputHandler();
        }
        update(deltaTime){
            this.player.update(this.input.keys, deltaTime)
        }
        draw(context){
            this.player.draw(context);
        }
    }

    const game= new Game(canvas.width, canvas.height)
    let lastTime = 0;

    function animate(timestamp){ // timestamp generated by requestanimation frame
        const deltaTime = timestamp - lastTime;
        /**Delta time gives off the numeric difference between the appearance of frames */
        // console.log('deltatime -> ', deltaTime)
        lastTime = timestamp;
        ctx.clearRect(0, 0, canvas.width, canvas.height)
        game.update(deltaTime);
        game.draw(ctx);
        requestAnimationFrame(animate);
    }

    animate(0);
})
